server:
  port: 8080

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/bai2
    username: postgres
    password: postgres

  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        format_sql: true
  flyway:
    enabled: true
